export const celebrities = [
  {
    first_name: "Elon",
    last_name: "Musk",
    age: 50,
    email: "elon.musk@example.com",
    address: {
      street: "SpaceX Blvd",
      city: "Los Angeles",
      state: "CA",
      zipCode: "54321",
    },
    hobbies: ["Inventing", "Space Exploration", "Twitter"],

    bio: "Entrepreneur, inventor, and CEO known for founding SpaceX and Tesla.",
    occupation: "CEO",
    country_of_origin: "United States",
    relationship_status: "Divorced",
  },
  {
    first_name: "Oprah",
    last_name: "Winfrey",
    age: 68,
    email: "oprah.winfrey@example.com",
    address: {
      street: "Harpo Studios",
      city: "Chicago",
      state: "IL",
      zipCode: "98765",
    },
    hobbies: ["Media Production", "Philanthropy", "Book Club"],
    bio: "Media mogul, talk show host, and philanthropist with a passion for literature.",
    occupation: "Media Mogul",
    country_of_origin: "United States",
    relationship_status: "Single",
  },

  {
    first_name: "Beyoncé",
    last_name: "Knowles",
    age: 40,
    email: "beyonce.knowles@example.com",
    address: {
      street: "Music Ave",
      city: "Houston",
      state: "TX",
      zipCode: "13579",
    },
    hobbies: ["Singing", "Dancing", "Acting"],
    bio: "International music icon, singer, and actress with a powerful stage presence.",
    occupation: "Musician",
    country_of_origin: "United States",
    relationship_status: "Married",
  },
  {
    first_name: "Cristiano",
    last_name: "Ronaldo",
    age: 37,
    email: "cristiano.ronaldo@example.com",
    address: {
      street: "Soccer Stadium",
      city: "Turin",
      state: "Piemonte",
      zipCode: "24680",
    },
    hobbies: ["Football", "Fitness", "Fashion"],
    bio: "Renowned footballer and fitness enthusiast with a passion for fashion.",
    occupation: "Footballer",
    country_of_origin: "Portugal",
    relationship_status: "In a Relationship",
  },
  {
    first_name: "Angela",
    last_name: "Merkel",
    age: 68,
    email: "angela.merkel@example.com",
    address: {
      street: "Chancellor's Office",
      city: "Berlin",
      state: "Berlin",
      zipCode: "86420",
    },
    hobbies: ["Politics", "Reading", "Hiking"],

    bio: "Former Chancellor of Germany known for her leadership in European politics.",
    occupation: "Politician",
    country_of_origin: "Germany",
    relationship_status: "Widowed",
  },
  {
    first_name: "Malala",
    last_name: "Yousafzai",
    age: 24,
    email: "malala.yousafzai@example.com",
    address: {
      street: "Education Street",
      city: "Birmingham",
      state: "England",
      zipCode: "97531",
    },
    hobbies: ["Education Advocacy", "Writing", "Public Speaking"],
    bio: "Nobel laureate and advocate for girls' education worldwide.",
    occupation: "Activist",
    country_of_origin: "Pakistan",
    relationship_status: "Single",
  },
  {
    first_name: "LeBron",
    last_name: "James",
    age: 37,
    email: "lebron.james@example.com",
    address: {
      street: "Basketball Court",
      city: "Los Angeles",
      state: "CA",
      zipCode: "75321",
    },
    hobbies: ["Basketball", "Business", "Philanthropy"],
    bio: "NBA superstar, businessman, and philanthropist committed to social causes.",
    occupation: "Basketball Player",
    country_of_origin: "United States",
    relationship_status: "Married",
  },

  {
    first_name: "Adele",
    last_name: "Adkins",
    age: 33,
    email: "adele.adkins@example.com",
    address: {
      street: "Music Lane",
      city: "London",
      state: "England",
      zipCode: "25814",
    },
    hobbies: ["Singing", "Songwriting", "Cooking"],
    bio: "Grammy-winning singer-songwriter with a soulful voice and a love for cooking.",
    occupation: "Musician",
    country_of_origin: "United Kingdom",
    relationship_status: "Divorced",
  },
];
