export const celebrities = [
  {
    first_name: "イーロン",
    last_name: "マスク",
    image: "/image/space_rocket.png",
    age: 50,
    hobbies: ["発明", "宇宙探査", "Twitter", "X", "SNS"],
    bio: "起業家、発明家、スペースXおよびテスラの創設者として知られています。",
    occupation: "CEO",
    country_of_origin: "アメリカ合衆国",
    relationship_status: "離婚済み",
  },
  {
    first_name: "ビヨンセ",
    last_name: "ノウルズ",
    image: "/image/music_singer_woman.png",
    age: 40,
    hobbies: ["歌唱", "ダンス", "演技"],
    bio: "国際的な音楽アイコンであり、力強いステージプレゼンスを持つ歌手および女優。",
    occupation: "ミュージシャン",
    country_of_origin: "アメリカ合衆国",
    relationship_status: "結婚中",
  },
  {
    first_name: "クリスティアーノ",
    last_name: "ロナウド",
    image: "/image/sport_soccerball.png",
    age: 37,
    hobbies: ["サッカー", "フィットネス", "ファッション"],
    bio: "著名なサッカー選手であり、フィットネス愛好家でファッションへの情熱を持つ。",
    occupation: "サッカー選手",
    country_of_origin: "ポルトガル",
    relationship_status: "交際中",
  },
  {
    first_name: "リオネル",
    last_name: "メッシ",
    image: "/image/sport_soccerball.png",
    age: 37,
    hobbies: ["サッカー", "家族", "慈善活動"],
    bio: "世界的に有名なサッカー選手で、歴代最高の選手の一人と広く考えられています。",
    occupation: "サッカー選手",
    country_of_origin: "アルゼンチン",
    relationship_status: "結婚中",
  },
  {
    first_name: "ショウヘイ",
    last_name: "オオタニ",
    image: "/image/baseball.png",
    age: 30,
    hobbies: ["野球", "トレーニング", "映画鑑賞"],
    bio: "野球で投手と打者の二役をこなすことで知られる、世界的に有名なアスリート。",
    occupation: "プロ野球選手",
    country_of_origin: "日本",
    relationship_status: "結婚中",
  },
  {
    first_name: "ジョージ",
    last_name: "ルース",
    image: "/image/baseball.png",
    age: 53,
    hobbies: ["野球", "ゴルフ", "映画観賞"],
    bio: "アメリカの元プロ野球選手で、野球史上最も偉大な打者の一人とされています。ニューヨーク・ヤンキースでのキャリアを通じて、714本のホームランを記録し、その功績は今日でも称賛されています。",
    occupation: "元プロ野球選手",
    country_of_origin: "アメリカ合衆国",
    relationship_status: "既婚",
  },
  {
    first_name: "キア",
    last_name: "スターマー",
    image: "/image/seijika.png",
    age: 62,
    hobbies: ["政治", "読書", "運動"],
    bio: "イギリスの第80代首相であり、第22代労働党党首。弁護士としても知られ、労働党のリーダーとして国内政策や外交問題に取り組んでいる。",
    occupation: "首相",
    country_of_origin: "イギリス",
    relationship_status: "既婚",
  },
  {
    first_name: "レブロン",
    last_name: "ジェームズ",
    image: "/image/basketball.png",
    age: 37,
    hobbies: ["バスケットボール", "ビジネス", "慈善活動"],
    bio: "NBAスーパースターであり、ビジネスマン、慈善家として社会貢献にコミットしています。",
    occupation: "バスケットボール選手",
    country_of_origin: "アメリカ合衆国",
    relationship_status: "結婚中",
  },
  {
    first_name: "マイケル",
    last_name: "ジョーダン",
    image: "/image/basketball.png",
    age: 61,
    hobbies: ["バスケットボール", "ゴルフ", "ビジネス", "慈善活動"],
    bio: "アメリカの元プロバスケットボール選手で、NBA史上最も偉大な選手の一人とされています。シカゴ・ブルズでのキャリアを通じて、6度のNBAチャンピオンシップを獲得しました。引退後はビジネスマンや慈善活動家としても成功を収めています。",
    occupation: "元プロバスケットボール選手",
    country_of_origin: "アメリカ合衆国",
    relationship_status: "既婚",
  },
  {
    first_name: "宮崎",
    last_name: "駿",
    image: "/image/kantoku.png",
    age: 83,
    hobbies: ["アニメ制作", "読書", "自然散策"],
    bio: "著名なアニメ映画監督で、スタジオジブリの創設者として知られています。",
    occupation: "アニメ映画監督",
    country_of_origin: "日本",
    relationship_status: "既婚",
  },
  {
    first_name: "ジョー",
    last_name: "バイデン",
    image: "/image/seijika.png",
    age: 81,
    hobbies: ["政治", "家族", "歴史"],
    bio: "第46代アメリカ合衆国大統領で、長年の政治経験を持ち、アメリカの民主主義を守ることに努めています。",
    occupation: "大統領",
    country_of_origin: "アメリカ合衆国",
    relationship_status: "既婚",
  },
  {
    first_name: "ドナルド",
    last_name: "トランプ",
    image: "/image/trump.png",
    age: 78,
    hobbies: ["ビジネス", "ゴルフ", "メディア"],
    bio: "第45代アメリカ合衆国大統領で、ビジネスマンおよびメディアパーソナリティとしても知られています。",
    occupation: "前大統領",
    country_of_origin: "アメリカ合衆国",
    relationship_status: "既婚",
  },
  {
    first_name: "文雄",
    last_name: "岸田",
    image: "/image/seijika.png",
    age: 66,
    hobbies: ["読書", "ゴルフ", "旅行"],
    bio: "日本の政治家で、自由民主党の一員。2021年10月に日本の第100代内閣総理大臣に就任し、外交政策や経済改革を推進しています。前任者の政策を継承しつつ、新たなビジョンを掲げています。",
    occupation: "首相",
    country_of_origin: "日本",
    relationship_status: "既婚",
  },
  {
    first_name: "トラビス",
    last_name: "スコット",
    image: "/image/rapper.png",
    age: 32,
    hobbies: ["音楽制作", "ファッション", "旅行", "USラッパー"],
    bio: "アメリカのラッパー、音楽プロデューサーで、ヒップホップ界の影響力のあるアーティストの一人。独自の音楽スタイルとファッションセンスで知られています。",
    occupation: "ラッパー",
    country_of_origin: "アメリカ合衆国",
    relationship_status: "交際中",
  },
  {
    first_name: "ドレイク",
    last_name: "グラハム",
    image: "/image/rapper.png",
    age: 37,
    hobbies: ["音楽制作", "俳優", "ファッション", "バスケットボール"],
    bio: "カナダ出身のラッパー、シンガー、ソングライターで、ヒップホップとR&Bの界で著名なアーティスト。数多くのヒット曲とアルバムを持ち、音楽業界で広く認識されています。",
    occupation: "ラッパー",
    country_of_origin: "カナダ",
    relationship_status: "未婚",
  },
  {
    first_name: "ケンドリック",
    last_name: "ラマー",
    image: "/image/rapper.png",
    age: 36,
    hobbies: ["音楽制作", "文学", "社会問題への取り組み"],
    bio: "アメリカのラッパー、ソングライターで、革新的な音楽スタイルと深いリリックで知られるアーティスト。社会的なテーマを扱った歌詞が特徴で、多くの賞を受賞しています。",
    occupation: "ラッパー",
    country_of_origin: "アメリカ合衆国",
    relationship_status: "既婚",
  },
];
